# Generated by Django 4.1.6 on 2023-02-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='store.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='store.product'),
            preserve_default=False,
        ),
    ]
