# Generated by Django 4.1.6 on 2023-02-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_delete_likeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedItemManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
